# Generated by Django 4.0.6 on 2022-08-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, db_column='cliente', max_length=255, null=True)),
                ('restaurante', models.CharField(blank=True, db_column='restaurante', max_length=255, null=True)),
            ],
            options={
                'db_table': 'lista',
                'managed': False,
            },
        ),
    ]
