# Generated by Django 4.0.6 on 2022-08-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0002_lista'),
    ]

    operations = [
        migrations.CreateModel(
            name='disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(blank=True, db_column='Categoria', max_length=255, null=True)),
                ('Produto', models.CharField(blank=True, db_column='Produto', max_length=255, null=True)),
                ('Disponibilidade', models.CharField(blank=True, db_column='Disponibilidade', max_length=255, null=True)),
                ('DATA', models.DateField(blank=True, db_column='DATA', max_length=255, null=True)),
                ('LOJA', models.CharField(blank=True, db_column='LOJA', max_length=255, null=True)),
            ],
            options={
                'db_table': 'disponibilidade',
                'managed': False,
            },
        ),
    ]
