# Generated by Django 4.0.6 on 2022-08-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0003_disponibilidade'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nc_financeiro',
            table='nc_financeiro',
        ),
    ]
