# Generated by Django 4.0.6 on 2022-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0004_alter_nc_financeiro_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.CharField(blank=True, db_column='Cliente', max_length=255, null=True)),
                ('DATA', models.DateField(blank=True, db_column='DATA', max_length=255, null=True)),
                ('Pedido', models.CharField(blank=True, db_column='Pedido', max_length=255, null=True)),
                ('Data_do_pedido', models.CharField(blank=True, db_column='Data_do_pedido', max_length=255, null=True)),
                ('Avaliacao', models.CharField(blank=True, db_column='Avaliação', max_length=255, null=True)),
                ('Data_do_avaliação', models.CharField(blank=True, db_column='Data_do_avaliação', max_length=255, null=True)),
                ('Comentário', models.CharField(blank=True, db_column='Comentário', max_length=255, null=True)),
                ('Status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('Unnamed_6', models.CharField(blank=True, db_column='Unnamed_6', max_length=255, null=True)),
                ('Loja', models.CharField(blank=True, db_column='Loja', max_length=255, null=True)),
            ],
            options={
                'db_table': 'avaliacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.CharField(blank=True, db_column='Cliente', max_length=255, null=True)),
                ('Promoção', models.CharField(blank=True, db_column='Promoção', max_length=255, null=True)),
                ('Status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('DATA', models.DateField(blank=True, db_column='DATA', max_length=255, null=True)),
                ('Loja', models.CharField(blank=True, db_column='Loja', max_length=255, null=True)),
                ('Hora', models.CharField(blank=True, db_column='Hora', max_length=255, null=True)),
            ],
            options={
                'db_table': 'promocao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.CharField(blank=True, db_column='Cliente', max_length=255, null=True)),
                ('Data', models.CharField(blank=True, db_column='Data', max_length=255, null=True)),
                ('Loja', models.CharField(blank=True, db_column='Loja', max_length=255, null=True)),
                ('Hora', models.CharField(blank=True, db_column='Hora', max_length=255, null=True)),
                ('Tempo_de_Entrega', models.CharField(blank=True, db_column='Tempo de Entrega', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tempo',
                'managed': False,
            },
        ),
    ]
