# Generated by Django 4.1 on 2022-08-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0007_promocoes_delete_promocao'),
    ]

    operations = [
        migrations.CreateModel(
            name='metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, db_column='cliente', max_length=255, null=True)),
                ('restaurante', models.CharField(blank=True, db_column='restaurante', max_length=255, null=True)),
                ('data', models.DateField(blank=True, db_column='data', max_length=255, null=True)),
                ('meta', models.FloatField(blank=True, db_column='meta', max_length=255, null=True)),
            ],
            options={
                'db_table': 'metas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='metas_dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, db_column='cliente', max_length=255, null=True)),
                ('restaurante', models.CharField(blank=True, db_column='restaurante', max_length=255, null=True)),
                ('monday', models.FloatField(blank=True, db_column='monday', max_length=255, null=True)),
                ('tuesday', models.FloatField(blank=True, db_column='tuesday', max_length=255, null=True)),
                ('wednesday', models.FloatField(blank=True, db_column='wednesday', max_length=255, null=True)),
                ('thursday', models.FloatField(blank=True, db_column='thursday', max_length=255, null=True)),
                ('friday', models.FloatField(blank=True, db_column='friday', max_length=255, null=True)),
                ('saturday', models.FloatField(blank=True, db_column='saturday', max_length=255, null=True)),
                ('sunday', models.FloatField(blank=True, db_column='sunday', max_length=255, null=True)),
            ],
            options={
                'db_table': 'metas_dia',
                'managed': False,
            },
        ),
    ]
